// LOCALHOST


POST http://localhost:8080/contacts/ HTTP/1.1
Content-Type: application/json

{
  "firstName": "Kylee",
  "lastName": "Mecham",
  "email": "KMecham@gmail.com",
  "favoriteColor": "Black",
  "birthday": "06-16-1995"
}
